package main

import (
	"bytes"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestMain(m *testing.M) {
	root, err := filepath.EvalSymlinks(os.TempDir())
	if err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.Setenv("TMPDIR", root); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	os.Exit(m.Run())
}

func TestComments(t *testing.T) {
	tests := []struct{ name, source, rules string }{
		{"three", "// a\n// b\n// c", ""},
		{"four", "// a\n// b\n// c\n// d", "lines"},
		{"blank", "// a\n//\n// b\n// c", "lines"},
		{"block", "/*\n * a\n * b\n * c\n */", ""},
		{"same physical line", "/* a */ /* b */ /* c */ /* d */", ""},
		{"block four", "/* a\n b\n c\n d */", "lines"},
		{"ascii boundary", "// " + strings.Repeat("a", 200), ""},
		{"ascii wide", "// " + strings.Repeat("a", 201), "width"},
		{"japanese boundary", "// " + strings.Repeat("あ", 100), ""},
		{"japanese wide", "// " + strings.Repeat("あ", 100) + "a", "width"},
		{"tab boundary", "// " + strings.Repeat("a", 192) + "\t", ""},
		{"tab wide", "// " + strings.Repeat("a", 200) + "\t", "width"},
		{"indent", "//\t\t" + strings.Repeat("a", 200), ""},
		{"allow", "// a\n// b\n// c\n// d\n// commentlint:allow-long -- 契約の条件を併記", ""},
		{"reason missing", "// a\n// commentlint:allow-long -- ", "marker-format"},
		{"blank unicode reason", "// a\n// commentlint:allow-long -- 　", "marker-format"},
		{"unknown", "// a\n// commentlint:ignore -- 理由", "marker-format"},
		{"inline marker", "// a commentlint:allow-long -- 理由", "marker-format,marker-empty"},
		{"duplicate", "// a\n// commentlint:allow-long -- 理由\n// commentlint:allow-long -- 理由", "marker-duplicate"},
		{"empty", "// commentlint:allow-long -- 理由", "marker-empty"},
		{"marker width", "// a\n// commentlint:allow-long -- " + strings.Repeat("a", 200), "width"},
		{"allowed width", "// " + strings.Repeat("a", 201) + "\n// commentlint:allow-long -- 理由", "width"},
		{"directive literal", "//go:generate tool commentlint:example", ""},
		{"go directive with underscore", "//go:cgo_import_dynamic x\n// a\n// b\n// c", ""},
		{"spaced prose", "// go:noinline\n// a\n// b\n// c", "lines"},
		{"directive adjacent", "//go:noinline\n// a\n// b\n// c\n// d", "lines"},
		{"directive", "//go:noinline\n// a\n// b\n// c", ""},
		{"nolint", "//nolint:errcheck // " + strings.Repeat("a", 201), ""},
		{"legacy build", "// +build linux\n// a\n// b\n// c", ""},
		{"line directive", "//line other.go:1\n// a\n// b\n// c", ""},
		{"separate groups", "// commentlint:allow-long -- 理由\n\n// a\n// b\n// c\n// d", "marker-empty,lines"},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			fset := token.NewFileSet()
			file, err := parser.ParseFile(fset, "input.go", "package p\n"+test.source+"\nvar x int\n", parser.ParseComments)
			if err != nil {
				t.Fatal(err)
			}
			var rules []string
			for _, group := range file.Comments {
				for _, issue := range checkGroup("input.go", commentLines(fset, group)) {
					rules = append(rules, issue.rule)
				}
			}
			if got := strings.Join(rules, ","); got != test.rules {
				t.Fatalf("got %q, want %q", got, test.rules)
			}
		})
	}
}

func TestDisplayWidth(t *testing.T) {
	for _, test := range []struct {
		text string
		want int
	}{{"ｶα", 2}, {"あa\tb", 9}, {"🀄", 2}, {"e\u0301", 2}} {
		if got := displayWidth(test.text); got != test.want {
			t.Errorf("%q: got %d want %d", test.text, got, test.want)
		}
	}
}

func TestRun(t *testing.T) {
	root := t.TempDir()
	for _, directory := range []string{"cmd", "internal", "migrations", "tools"} {
		if err := os.Mkdir(filepath.Join(root, directory), 0o700); err != nil {
			t.Fatal(err)
		}
	}
	write := func(name, source string) {
		t.Helper()
		if err := os.WriteFile(filepath.Join(root, name), []byte(source), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	write("cmd/string.go", "package p\nvar s = `// a\n// b\n// c\n// d`\n")
	write("cmd/generated.go", "// Code generated by test. DO NOT EDIT.\npackage p\n// a\n// b\n// c\n// d\nvar x int\n")
	outside := t.TempDir()
	if err := os.WriteFile(filepath.Join(outside, "bad.go"), []byte("invalid"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, filepath.Join(root, "cmd", "linked")); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(filepath.Join(outside, "bad.go"), filepath.Join(root, "cmd", "linked.go")); err != nil {
		t.Fatal(err)
	}
	var out bytes.Buffer
	if code := run(root, &out); code != 0 {
		t.Fatalf("%d: %s", code, out.String())
	}
	write("internal/example_windows_test.go", "//go:build windows\n\npackage p\n// a\n// b\n// c\n// d\nvar x int\n")
	write("tools/end.go", "package p\nvar x int // "+strings.Repeat("a", 201)+"\n")
	if code := run(root, &out); code != 1 {
		t.Fatalf("got %d", code)
	}
	if !strings.Contains(out.String(), "example_windows_test.go:4: lines: actual=4") || !strings.Contains(out.String(), "end.go:2: width: actual=201") {
		t.Fatal(out.String())
	}
	first := out.String()
	out.Reset()
	run(root, &out)
	if first != out.String() {
		t.Fatal("unstable output")
	}
	write("migrations/broken.go", "package")
	out.Reset()
	if run(root, &out) != 1 || !strings.Contains(out.String(), "parse/read:") {
		t.Fatal(out.String())
	}
	out.Reset()
	if run(filepath.Join(root, "missing"), &out) != 1 {
		t.Fatal("missing root accepted")
	}
}
