package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// layout は cmd/internal/tools 配下にファイルを並べた検査対象のrootを作る。
func layout(t *testing.T, exclusions string, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, exclusionsFileName), []byte(exclusions), 0o600); err != nil {
		t.Fatal(err)
	}
	for _, directory := range []string{"cmd", "internal", "tools"} {
		if err := os.Mkdir(filepath.Join(root, directory), 0o700); err != nil {
			t.Fatal(err)
		}
	}
	for name, content := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func TestMapTestFile(t *testing.T) {
	impls := map[string]bool{"store": true, "store_edges": true, "slots": true}
	for _, test := range []struct {
		base string
		want string
	}{
		{"store", "store"},
		{"store_edges", "store_edges"},
		{"store_coverage", "store"},
		{"slots_edges_matrix", "slots"},
		{"layout", ""},
	} {
		t.Run(test.base, func(t *testing.T) {
			if got := mapTestFile(test.base, impls); got != test.want {
				t.Fatalf("mapTestFile(%q) = %q, want %q", test.base, got, test.want)
			}
		})
	}
}

func TestPlatformVariant(t *testing.T) {
	for base, want := range map[string]bool{"identity_darwin": true, "usage_linux": true, "store": false, "slot_allocation": false} {
		if got := platformVariant(base); got != want {
			t.Fatalf("platformVariant(%q) = %v, want %v", base, got, want)
		}
	}
}

// 登録のない欠落だけがmake ciを落とし、観点別のテストファイル名は最長一致で対応づく。
func TestRunReportsMissingTestFile(t *testing.T) {
	root := layout(t, "", map[string]string{
		"internal/state/store.go":            "package state\n",
		"internal/state/store_edges_test.go": "package state\n",
		"internal/state/slots.go":            "package state\n",
	})
	var out bytes.Buffer
	if code := run(root, &out); code != 1 {
		t.Fatalf("run() = %d, want 1", code)
	}
	got := out.String()
	if !strings.Contains(got, "internal/state/slots.go:1: test-layout: no test file is named after this implementation file") {
		t.Fatalf("output %q lacks the violation", got)
	}
	if strings.Contains(got, "store.go:1:") {
		t.Fatalf("output %q unexpectedly reports store.go", got)
	}
	if !strings.Contains(got, guidance[0]) {
		t.Fatalf("output %q lacks the guidance", got)
	}
}

// exemptは黙って外し、backlogは警告として残すが失敗させない。
func TestRunHonorsExclusionKinds(t *testing.T) {
	exclusions := "internal/state/slots.go\tbacklog\tSplit out of store.go.\ninternal/state/gc.go\texempt\tAdapter covered elsewhere.\n"
	root := layout(t, exclusions, map[string]string{
		"internal/state/slots.go": "package state\n",
		"internal/state/gc.go":    "package state\n",
	})
	var out bytes.Buffer
	if code := run(root, &out); code != 0 {
		t.Fatalf("run() = %d, want 0; output %q", code, out.String())
	}
	got := out.String()
	if !strings.Contains(got, "internal/state/slots.go:1: test-layout: no test file is named after this implementation file; known backlog") {
		t.Fatalf("output %q lacks the backlog warning", got)
	}
	if strings.Contains(got, "gc.go") {
		t.Fatalf("output %q unexpectedly reports the exempt file", got)
	}
}

// 対応済みになったbacklogを残すと免除が実態から離れるため、失敗させる。
func TestRunRejectsStaleBacklog(t *testing.T) {
	root := layout(t, "internal/state/slots.go\tbacklog\tSplit out of store.go.\n", map[string]string{
		"internal/state/slots.go":      "package state\n",
		"internal/state/slots_test.go": "package state\n",
	})
	var out bytes.Buffer
	if code := run(root, &out); code != 1 {
		t.Fatalf("run() = %d, want 1", code)
	}
	if !strings.Contains(out.String(), "stale backlog entry") {
		t.Fatalf("output %q lacks the stale entry failure", out.String())
	}
}

// 理由と種別のない行は免除として認めない。
func TestRunRejectsMalformedExclusions(t *testing.T) {
	for name, exclusions := range map[string]string{
		"no reason": "internal/state/slots.go\tbacklog\n",
		"bad kind":  "internal/state/slots.go\tskip\tReason.\n",
	} {
		t.Run(name, func(t *testing.T) {
			root := layout(t, exclusions, map[string]string{"internal/state/slots.go": "package state\n"})
			var out bytes.Buffer
			if code := run(root, &out); code != 1 {
				t.Fatalf("run() = %d, want 1", code)
			}
			if !strings.Contains(out.String(), exclusionsFileName+":1:") {
				t.Fatalf("output %q lacks the exclusions file error", out.String())
			}
		})
	}
}

// 生成物とGOOS別のファイルは基のファイル側で検査するため、テストファイルを求めない。
func TestRunSkipsGeneratedAndPlatformFiles(t *testing.T) {
	root := layout(t, "", map[string]string{
		"internal/state/enum.go":            "// Code generated by stringer. DO NOT EDIT.\npackage state\n",
		"internal/state/identity_darwin.go": "package state\n",
	})
	var out bytes.Buffer
	if code := run(root, &out); code != 0 {
		t.Fatalf("run() = %d, want 0; output %q", code, out.String())
	}
	if out.String() != "" {
		t.Fatalf("output = %q, want empty", out.String())
	}
}
